DROP PROCEDURE NewsletterJobGetAll
DROP PROCEDURE NewsletterJobCreate
DROP PROCEDURE NewsletterJobDelete
DROP PROCEDURE NewsletterJobEdit
DROP PROCEDURE NewsletterRecipientListAddEmail
DROP PROCEDURE NewsletterRecipientListCreate
DROP PROCEDURE NewsletterRecipientListDelete
DROP PROCEDURE NewsletterRecipientListEdit
DROP PROCEDURE NewsletterRecipientListRemoveEmail
DROP PROCEDURE NewsletterWorkItemAdd
DROP PROCEDURE NewsletterWorkItemChangeStatus
DROP PROCEDURE NewsletterWorkItemChangeStatusAndInfo
DROP PROCEDURE NewsletterWorkItemDeleteAllForJob
GO